FROM debian:trixie-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        vim \
        tmux \
        openssh-client \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*
