FROM quay.io/fedora/fedora:latest

RUN dnf install -y python3 python3-pip make npm \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && useradd -m -s /bin/bash dev \
    && echo "dev ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/dev \
    && chmod 0440 /etc/sudoers.d/dev

USER dev
WORKDIR /home/dev

CMD ["/bin/bash"]
