services:
  mc:
    image: docker.io/itzg/minecraft-server@sha256:46919d151d39e89993c40fa3cedddd200b1bbb4aa44217e17a638c047817b9f4
    tty: true
    stdin_open: true

    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"

    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data:

